### ISSUE TITLE
Input Search Filter

### ISSUE THREAD

**Issue by toddchannick** [s-yadav/angulargrid#24]
Is there anyway to trigger a refresh after executing a search filter (ng-repeat="image in images | filter:searchText") on an input box?

The filter works; however, when I clear the input box, all of the elements of the grid return stacked on one another (upon inspection, I see they no longer have a class of "img-loaded", and have lost their "top", "left", and "width" style attributes)

Thank you!

**Comment by toddchannick** [comment]
Ok, I got it to work by moving my filter out of the angular expression and into to the controller...however, once i clear my text from the input field, it doesn't refresh the layout. Here is my code:

<pre><code>
$scope.$watch('searchText',function(val){
    val = val.toLowerCase();
    $scope.bookmarks = $scope.bookmarks.filter(function(obj){
        return obj.title.toLowerCase().indexOf(val) != -1;
    });
  });
</code></pre>

Any idea what could be causing this issue?

**Comment by s-yadav** [comment]
I hope you already have figured out your problem,
The problem lies here 
```js
$scope.bookmarks = $scope.bookmarks.filter(function(obj){
        return obj.title.toLowerCase().indexOf(val) != -1;
    });
```
You are filtering on a array and storing on same model again, so next time you type something it will filter the filtered array, and at the end it will be empty. Try this.

```js
var bookmarks = $scope.bookmarks;
$scope.$watch('searchText',function(val){
    val = val.toLowerCase();
    $scope.bookmarks = bookmarks.filter(function(obj){
        return obj.title.toLowerCase().indexOf(val) != -1;
    });
  });
```

Moreover angular filter does not affect the same model, it creates a new model, so angulargrid can't figureout when to refresh the grids. This is one limitation, which need to be handled using manual watching and filtering.

**Comment by toddchannick** [comment]
Great, thanks so much for your help
