### ISSUE TITLE
Performant scroll - items not displaying

### ISSUE THREAD

**Issue by tomwasd** [s-yadav/angulargrid#50]
Hi,

Firstly, thanks for creating this - it's great and a lot better than a home grown solution I was using 👍 

I'm using the grid within an Ionic (Cordova) app but I'm having a few issues with performant scroll.

If I load the page with the angulargrid but then rapidly switch to another page (which I believe in Ionic detaches any listeners) before returning to the page with the angulargrid I get a blank page.

All the items in the grid appear to have been detached due to the performant scroll. However, scrolling up or down doesn't trigger them to reappear. Nor does calling `refresh` on the angulargrid instance or by manually calling `handleScroll`

The only way I can fix it is by inserting more items into the model (which angulargrid is watching) - which I presume triggers `ng-repeat` to update the DOM.

I've had a play about with the source to try and fix the issue but haven't had much luck.

I hope my rambling above makes sense but if you need any clarification just shout. Fingers crossed someone knows whats going on :)

Thanks a lot,

Tom

**Comment by s-yadav** [comment]
I have not tested it with Ionic, but I guess as Ionic uses custom scroll instead of native, angulargrid not able to get the scroll event.

So you can use on-scroll event handler of ionic scroll and within that event call handleScroll method of angulargrid. See "Integrating with custom scroll plugins " in http://ignitersworld.com/lab/angulargrid/ .

Let me know if this fix your issue.

**Comment by s-yadav** [comment]
Closing it. Open it with fiddle, if anyone else get into same problem.
